### ISSUE TITLE
Ишьюсы к РК3

### ISSUE THREAD

**Issue by KOPTE3** [frontend-park-mail-ru/2017_2_glitchless#15]
# Исправления к РК3

- [x] в горизонтальном виде на мобилках ваше приложение выглядит очень странно
- [x] когда открывается меню авторизации в попапе &mdash; это выглядит очень круто, зачёт. Но при этом меню на заднем фоне всё равно активно и на него можно кликнуть. Сделайте так, чтобы форма регистрации/авторизации открывалось в настоящем попапе, чтобы при этом всё, что на фоне стеновилось недоступным, чтобы появлялся скролл...
- [x] заходим на `https://glitchless.ru/signup` и получаем 404... Epic fail. Настройте роутинг на сервере
- [x] минифицируйте статику (js, css, html) во время сборки
- [x] [MIME-типы](https://stackoverflow.com/questions/21098865/text-javascript-vs-application-javascript)
- [x] Почитайте про `reset.css` и `normalize.css`
- [x] JS-ошибки в консоли при запуске и работе приложения
- [x] Если положить в папку `/some-view` файл `index.js`, то можно будет его импортить `import SomeView from './some-view'` вместо `import SomeView from './some-view/view.js'`. Синк эбаут ит!
- [x] https://developer.mozilla.org/ru/docs/Mozilla/Mobile/Viewport_meta_tag
- [x] сервис-воркер =(((
- [x] не кешируйте несколько раз `index.html`
- [x] не хардкодить список файлов в сервисворкере (либо генерить его вебпаком, либо кэшировать динамически)
- [x] надо починить что-то что ломается при двух загрузках PIXI
- [x] не ресайзится игровое окно при ресайзе вьюпорта
- [x] ХАЧУ ФУЛСКИН!!!!111!1
- [x] не надо перехватывать `cmd/ctrl + R`
- [x] игра вроде работает) так что за это не буду снимать баллы, ну, максимум, один)

**Comment by KOPTE3** [comment]
Сервис-воркер до сих пор не работает

**Comment by reo7sp** [comment]
@KOPTE3 поправили сервис воркер

**Comment by reo7sp** [comment]
>не кешируйте несколько раз index.html
https://github.com/frontend-park-mail-ru/2017_2_glitchless/blob/site-base/src/sw-index.ts#L36

>не хардкодить список файлов в сервисворкере (либо генерить его вебпаком, либо кэшировать динамически)
https://github.com/frontend-park-mail-ru/2017_2_glitchless/blob/site-base/src/sw-index.ts#L4

**Comment by KOPTE3** [comment]
# Done
