### ISSUE TITLE
РК#4:after

### ISSUE THREAD

**Issue by avtyul** [frontend-park-mail-ru/2017_2_glitchless#18]
Привет

Вы крутые, деплой через докер и ансибл - это вышка!

Доведите плиз игру до ума, сделайте бота умнее

И Никита что-то говорил про ссылки, ведущие прямо в лобби (рассмотрите идею с комнатами) / игру

**Comment by LionZXY** [comment]
Привет! Нам как-то надо на это реагировать?

**Comment by avtyul** [comment]
@LionZXY ну с точки зрения баллов - у вас всё ок, последние две строчки скорее про крутую защиту, тут сами решайте

**Comment by LionZXY** [comment]
Да, конечно. Добавили в туду ещё после РК :) Сделаем
